### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AshStranger** [TJPlaysNow/ConfigAPI#2]
```
public Config config;
config = new Config("plugins/test", "config.yml", this);
config.getConfig().set("itemArms.lightsaberblue.enable", true);
config.saveConfig();

```

```
Error occurred while enabling MoreItemsPack v0.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/pzg/www/api/config/Config
	at com.github.AshStranger.mainPack.onEnable(mainPack.java:43) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[paper1112.jar:git-Paper-1040]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [paper1112.jar:git-Paper-1040]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paper1112.jar:git-Paper-1040]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [paper1112.jar:git-Paper-1040]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [paper1112.jar:git-Paper-1040]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:433) [paper1112.jar:git-Paper-1040]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:394) [paper1112.jar:git-Paper-1040]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:332) [paper1112.jar:git-Paper-1040]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [paper1112.jar:git-Paper-1040]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [paper1112.jar:git-Paper-1040]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: com.pzg.www.api.config.Config
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[paper1112.jar:git-Paper-1040]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paper1112.jar:git-Paper-1040]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 12 more
```

**Comment by TJPlaysNow** [comment]
I believe that is caused because you did not have the class saved in your own code, or you did not have the Config API plugin saved in your plugins folder.
